export const mobilePage = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>ShowWhere 모바일 리모트</title><style>
:root{font-family:Inter,Pretendard,system-ui,sans-serif;color:#241f20;background:#f6f3f3}*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:20px}.card{width:min(100%,430px);background:#fff;border:1px solid #e4dede;border-radius:24px;padding:28px;box-shadow:0 20px 60px #47232320;text-align:center}.gorilla{width:132px;height:132px;object-fit:contain}.brand{font-size:27px;font-weight:850;color:#472323;margin:4px 0}.sub{color:#71696b;line-height:1.55;margin:8px 0 24px}button,input{width:100%;min-height:52px;border-radius:13px;font-size:17px}button{border:0;background:#472323;color:#fff;font-weight:750;cursor:pointer;padding:13px}button.secondary{background:#f2eeee;color:#472323;border:1px solid #d7cbcb;margin-top:10px}input{border:2px solid #d8cece;text-align:center;letter-spacing:.25em;font-weight:800;padding:10px;margin:8px 0 14px}.hidden{display:none!important}.status{min-height:24px;color:#71696b;margin-top:14px}.chat{height:52dvh;overflow:auto;text-align:left;background:#f7f5f5;border-radius:16px;padding:12px;margin:16px 0}.bubble{max-width:88%;padding:11px 13px;border-radius:15px;margin:8px 0;white-space:pre-wrap}.user{margin-left:auto;background:#472323;color:#fff}.assistant{background:#fff;border:1px solid #e0dada}.pending{opacity:.62}.row{display:flex;gap:8px}.row input{letter-spacing:0;text-align:left;margin:0;flex:1}.row button{width:auto}.dot{display:inline-block;width:10px;height:10px;background:#23a35a;border-radius:50%;margin-right:7px}video{width:100%;border-radius:14px;background:#111;margin:12px 0}
</style></head><body><main class="card">
<section id="start"><img class="gorilla" src="/mobile/gorilla.png" alt="ShowWhere 고릴라"><h1 class="brand">SHOWWHERE</h1><p class="sub">휴대폰을 키보드처럼 연결해<br>PC 화면의 길을 물어보세요.</p><button id="scan">PC와 연결하기</button><p class="status" id="cameraStatus"></p><video id="camera" class="hidden" playsinline></video></section>
<section id="verify" class="hidden"><img class="gorilla" src="/mobile/gorilla.png" alt="ShowWhere 고릴라"><h1 class="brand">인증번호 입력</h1><p class="sub">PC 화면에 표시된 6자리 숫자를 입력하세요.</p><input id="code" inputmode="numeric" maxlength="6" placeholder="000000"><button id="connect">연결</button><button id="back" class="secondary">다시 스캔</button><p class="status" id="verifyStatus"></p></section>
<section id="remote" class="hidden"><h1 class="brand">SHOWWHERE</h1><p><span class="dot"></span>PC와 연결됨</p><div id="chat" class="chat"></div><div class="row"><input id="message" placeholder="무엇을 하고 싶으세요?" maxlength="2000"><button id="send">보내기</button></div><button id="disconnect" class="secondary">연결 끊기</button></section>
</main><script>
const $=id=>document.getElementById(id);let token=new URLSearchParams(location.search).get('pair')||'';let stream=null,ws=null;
function page(id){for(const name of ['start','verify','remote'])$(name).classList.toggle('hidden',name!==id)}
if(token)page('verify');
async function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('camera').classList.add('hidden')}
$('scan').onclick=async()=>{if(!('BarcodeDetector'in window)){ $('cameraStatus').textContent='이 브라우저는 웹 QR 카메라를 지원하지 않아요. 휴대폰 기본 카메라로 PC의 QR을 스캔해 주세요.';return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});$('camera').srcObject=stream;$('camera').classList.remove('hidden');await $('camera').play();const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{if(!stream)return;for(const code of await detector.detect($('camera'))){try{const url=new URL(code.rawValue);const found=url.searchParams.get('pair');if(found){token=found;await stopCamera();page('verify');return}}catch{}}requestAnimationFrame(tick)};tick()}catch{$('cameraStatus').textContent='카메라 권한을 허용하거나 휴대폰 기본 카메라로 QR을 스캔해 주세요.'}};
$('back').onclick=()=>{token='';history.replaceState({},'',location.pathname);page('start')};
$('connect').onclick=async()=>{const code=[...$('code').value].filter(c=>c>='0'&&c<='9').join('');if(!token||code.length!==6){$('verifyStatus').textContent='PC의 6자리 인증번호를 확인해 주세요.';return}try{const response=await fetch('/api/pairing/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pairingToken:token,code})});if(!response.ok)throw 0;const data=await response.json();const protocol=location.protocol==='https:'?'wss:':'ws:';ws=new WebSocket(protocol+'//'+location.host+'/api/pairing/ws?role=mobile&sessionId='+encodeURIComponent(data.sessionId)+'&secret='+encodeURIComponent(data.mobileSecret));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='connection_status'){if(m.connected)page('remote');return}if(m.type==='chat_message')render(m)};ws.onclose=()=>{ws=null;page('start');$('cameraStatus').textContent='PC 연결이 종료됐어요. 다시 연결해 주세요.'};}catch{$('verifyStatus').textContent='번호가 다르거나 QR 유효시간이 지났어요. PC의 새 QR을 스캔해 주세요.'}};
function render(m){let el=document.getElementById('m-'+m.id);if(!el){el=document.createElement('div');el.id='m-'+m.id;el.className='bubble '+m.role;$('chat').appendChild(el)}el.textContent=m.text;el.classList.toggle('pending',m.isPending);$('chat').scrollTop=$('chat').scrollHeight}
function send(){const text=$('message').value.trim();if(!text||!ws||ws.readyState!==1)return;ws.send(JSON.stringify({type:'user_message',id:crypto.randomUUID(),text}));$('message').value=''}$('send').onclick=send;$('message').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send()}};$('disconnect').onclick=()=>ws?.close(1000,'mobile_disconnect');
</script></body></html>`;
