export const mobilePage = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#472323"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="ShowWhere"><link rel="apple-touch-icon" href="/mobile/gorilla.png"><link rel="icon" type="image/png" href="/mobile/gorilla.png"><link rel="manifest" href="/mobile/manifest.webmanifest">
<title>ShowWhere 모바일 리모트</title><style>
:root{font-family:Inter,Pretendard,system-ui,sans-serif;color:#241f20;background:#f6f3f3}*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:20px}.card{width:min(100%,430px);background:#fff;border:1px solid #e4dede;border-radius:24px;padding:28px;box-shadow:0 20px 60px #47232320;text-align:center}.gorilla{width:132px;height:132px;object-fit:contain}.brand{font-size:27px;font-weight:850;color:#472323;margin:4px 0}.sub{color:#71696b;line-height:1.55;margin:8px 0 24px}button,input{width:100%;min-height:52px;border-radius:13px;font-size:17px}button{border:0;background:#472323;color:#fff;font-weight:750;cursor:pointer;padding:13px}button:disabled{cursor:wait;opacity:.55}button.secondary{background:#f2eeee;color:#472323;border:1px solid #d7cbcb;margin-top:10px}input{border:2px solid #d8cece;text-align:center;letter-spacing:.25em;font-weight:800;padding:10px;margin:8px 0 14px}.hidden{display:none!important}.status{min-height:24px;color:#71696b;margin-top:14px;white-space:pre-wrap}.chat{height:52dvh;overflow:auto;text-align:left;background:#f7f5f5;border-radius:16px;padding:12px;margin:16px 0}.bubble{max-width:88%;padding:11px 13px;border-radius:15px;margin:8px 0;white-space:pre-wrap}.user{margin-left:auto;background:#472323;color:#fff}.assistant{background:#fff;border:1px solid #e0dada}.pending{opacity:.62}.row{display:flex;gap:8px}.row input{letter-spacing:0;text-align:left;margin:0;flex:1}.row button{width:auto}.dot{display:inline-block;width:10px;height:10px;background:#23a35a;border-radius:50%;margin-right:7px}video{width:100%;border-radius:14px;background:#111;margin:12px 0}
</style></head><body><main class="card">
<section id="start"><img class="gorilla" src="/mobile/gorilla.png" alt="ShowWhere 고릴라"><h1 class="brand">SHOWWHERE</h1><p class="sub">휴대폰을 키보드처럼 연결해<br>PC 화면의 길을 물어보세요.</p><button id="scan">PC와 연결하기</button><p class="status" id="cameraStatus"></p><video id="camera" class="hidden" playsinline></video></section>
<section id="verify" class="hidden"><img class="gorilla" src="/mobile/gorilla.png" alt="ShowWhere 고릴라"><h1 class="brand">인증번호 입력</h1><p class="sub">PC 화면에 표시된 6자리 숫자를 입력하세요.</p><input id="code" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="000000"><button id="connect">연결</button><button id="back" class="secondary">다시 스캔</button><p class="status" id="verifyStatus"></p></section>
<section id="remote" class="hidden"><h1 class="brand">SHOWWHERE</h1><p><span class="dot"></span>PC와 연결됨</p><div id="chat" class="chat" aria-live="polite"></div><div class="row"><input id="message" placeholder="무엇을 하고 싶으세요?" maxlength="2000"><button id="send">보내기</button></div><button id="disconnect" class="secondary">연결 끊기</button></section>
</main><script>
const $=id=>document.getElementById(id);let token=new URLSearchParams(location.search).get('pair')||'';let stream=null,ws=null,scanFrame=0,connectTimer=0,connecting=false;
function page(id){for(const name of ['start','verify','remote'])$(name).classList.toggle('hidden',name!==id)}
function randomId(){return globalThis.crypto&&typeof crypto.randomUUID==='function'?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
function resetPairing(message){token='';history.replaceState({},'',location.pathname);$('code').value='';$('verifyStatus').textContent='';page('start');$('cameraStatus').textContent=message||''}
function closeSocket(){clearTimeout(connectTimer);connectTimer=0;if(ws){const current=ws;ws=null;current.onclose=null;try{current.close(1000,'client_disconnect')}catch{}}}
if(token)page('verify');
async function stopCamera(){if(scanFrame)cancelAnimationFrame(scanFrame);scanFrame=0;if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}$('camera').classList.add('hidden');$('camera').srcObject=null}
$('scan').onclick=async()=>{try{await stopCamera();$('cameraStatus').textContent='카메라 권한을 허용한 뒤 QR을 맞춰 주세요.';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('camera').srcObject=stream;$('camera').classList.remove('hidden');await $('camera').play();if(!('BarcodeDetector'in window)){$('cameraStatus').textContent='카메라가 켜졌어요. QR 인식이 안 되면 iPhone 기본 카메라로 PC의 QR을 스캔해 주세요.';return}const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{if(!stream)return;try{for(const code of await detector.detect($('camera'))){try{const url=new URL(code.rawValue);const found=url.searchParams.get('pair');if(found){token=found;await stopCamera();$('verifyStatus').textContent='';page('verify');$('code').focus();return}}catch{}}}catch{$('cameraStatus').textContent='QR을 읽지 못했어요. 카메라를 QR에 다시 맞춰 주세요.'}if(stream)scanFrame=requestAnimationFrame(tick)};scanFrame=requestAnimationFrame(tick)}catch{await stopCamera();$('cameraStatus').textContent='카메라 권한을 허용하거나 휴대폰 기본 카메라로 QR을 스캔해 주세요.'}};
$('back').onclick=async()=>{closeSocket();await stopCamera();resetPairing('PC에 표시된 새 QR을 스캔해 주세요.')};
$('connect').onclick=async()=>{if(connecting)return;const code=[...$('code').value].filter(char=>char>='0'&&char<='9').join('');if(!token||code.length!==6){$('verifyStatus').textContent='PC의 6자리 인증번호를 확인해 주세요.';return}connecting=true;$('connect').disabled=true;$('verifyStatus').textContent='인증번호를 확인하고 있어요…';const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch('/api/pairing/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pairingToken:token,code}),signal:controller.signal});if(!response.ok)throw new Error('claim_failed');const data=await response.json();if(!data||typeof data.sessionId!=='string'||typeof data.mobileSecret!=='string')throw new Error('invalid_claim');closeSocket();const protocol=location.protocol==='https:'?'wss:':'ws:';ws=new WebSocket(protocol+'//'+location.host+'/api/pairing/ws?role=mobile&sessionId='+encodeURIComponent(data.sessionId),['showwhere-v1',data.mobileSecret]);$('verifyStatus').textContent='PC 연결을 기다리고 있어요…';connectTimer=setTimeout(()=>{if(ws&&ws.readyState!==WebSocket.OPEN){closeSocket();resetPairing('연결 시간이 초과됐어요. PC에서 새 QR을 열어 다시 연결해 주세요.')}},12000);ws.onopen=()=>{clearTimeout(connectTimer);connectTimer=0;$('verifyStatus').textContent='PC 연결을 기다리고 있어요…'};ws.onerror=()=>{if(ws&&ws.readyState!==WebSocket.OPEN){closeSocket();resetPairing('PC와 연결하지 못했어요. PC에서 새 QR을 열어 다시 시도해 주세요.')}};ws.onmessage=event=>{let message;try{message=JSON.parse(event.data)}catch{return}if(!message||typeof message!=='object')return;if(message.type==='connection_status'){if(message.connected)page('remote');else $('verifyStatus').textContent='PC 연결을 기다리고 있어요…';return}if(message.type==='chat_message')render(message)};ws.onclose=()=>{ws=null;resetPairing('PC 연결이 종료됐어요. PC에서 새 QR을 열어 다시 연결해 주세요.')}}catch(error){resetPairing(error&&error.name==='AbortError'?'서버 응답이 늦어 연결을 중단했어요. 새 QR로 다시 시도해 주세요.':'번호가 다르거나 QR 유효시간이 지났어요. PC에서 새 QR을 열어 주세요.')}finally{clearTimeout(timeout);connecting=false;$('connect').disabled=false}};
function render(message){if(typeof message.id!=='string'||(message.role!=='user'&&message.role!=='assistant')||typeof message.text!=='string')return;let element=document.getElementById('m-'+message.id);if(!element){element=document.createElement('div');element.id='m-'+message.id;element.className='bubble '+message.role;$('chat').appendChild(element)}element.textContent=message.text;element.classList.toggle('pending',message.isPending===true);$('chat').scrollTop=$('chat').scrollHeight}
function send(){const text=$('message').value.trim();if(!text||!ws||ws.readyState!==WebSocket.OPEN)return;ws.send(JSON.stringify({type:'user_message',id:randomId(),text}));$('message').value=''}$('send').onclick=send;$('message').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();send()}};$('disconnect').onclick=()=>{closeSocket();resetPairing('연결을 종료했어요.')};window.addEventListener('pagehide',()=>{stopCamera();closeSocket()});if(!token)setTimeout(()=>$('scan').click(),0);
</script></body></html>`;
